# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       meego-handset-camera

# >> macros
# << macros

Summary:    MeeGo Handset camera application
Version:    1.0.7
Release:    1
Group:      System/GUI/Other
License:    Apache License, Version 2.0
URL:        www.meego.com
Source0:    meego-handset-camera-%{version}.tar.bz2
Source100:  meego-handset-camera.yaml
Requires:   gst-plugins-camera
Requires:   gstreamer >= 0.10.32
Requires:   libdeclarative-multimedia
Requires:   gst-plugins-good
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  pkgconfig(QtOpenGL)
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(QtNetwork)
BuildRequires:  pkgconfig(QtMultimediaKit)
BuildRequires:  qt-devel-tools
BuildRequires:  desktop-file-utils

%description
meego-handset-camera provides very basic camera features such as still capture,
zooming, adjusting white balance, EV componesation and flash settings.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/meego-handset-camera
%{_datadir}/applications/meegocamera.desktop
%config %{_sysconfdir}/xdg/Nokia/%{name}.conf
# >> files
# << files
