# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       qmlcamera

# >> macros
# << macros

Summary:    Camera application for Nemo Mobile
Version:    1.0.7
Release:    1
Group:      System/GUI/Other
License:    Apache License, Version 2.0
URL:        https://github.com/nemomobile/qmlcamera
Source0:    %{name}-%{version}.tar.bz2
Source100:  qmlcamera.yaml
Requires:   gst-plugins-camera
Requires:   gstreamer >= 0.10.32
Requires:   libdeclarative-multimedia
Requires:   gst-plugins-good
BuildRequires:  pkgconfig(QtGui)
BuildRequires:  pkgconfig(QtOpenGL)
BuildRequires:  pkgconfig(QtDeclarative)
BuildRequires:  pkgconfig(QtNetwork)
BuildRequires:  pkgconfig(QtMultimediaKit)
BuildRequires:  qt-devel-tools
BuildRequires:  desktop-file-utils
Provides:   meego-handset-camera >= 1.0.7
Obsoletes:   meego-handset-camera < 1.0.7

%description
%{summary}.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qmake 

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}/meego-handset-camera
%{_datadir}/applications/meegocamera.desktop
%config %{_sysconfdir}/xdg/Nokia/meego-handset-camera.conf
# >> files
# << files
